version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    hostname: rabbitmq
    networks:
      - rabbitmqnet

  producer:
    build:
      context: ./RabbitMQLearn
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - rabbitmqnet
    depends_on:
      - rabbitmq

  subscriber:
    build:
      context: ./Subscriber
      dockerfile: Dockerfile
    networks:
      - rabbitmqnet
    depends_on:
      - rabbitmq

networks:
  rabbitmqnet:
    driver: bridge
