version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    hostname: rabbitmq
    networks:
      - rabbitmqnet

  producer:
    build:
      context: ./RabbitMQLearn
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
      - postgres-db
    networks:
      - rabbitmqnet

  consumer:
    build:
      context: ./Consumer
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    depends_on:
      - rabbitmq
    networks:
      - rabbitmqnet

  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=horizaD123++
     - POSTGRES_DB=RabbitMQ
    ports:
      - "5432:5432"
    networks:
      - rabbitmqnet
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  rabbitmqnet:
    driver: bridge
